ulx asay
ulx help
ulx motd
ulx psay
ulx thetime
ulx usermanagementhelp
ulx votemap
ulx who
ulx armor
ulx ban
ulx banindex
ulx blind
ulx bring
ulx chattime
ulx checkban
ulx cloak
ulx csay
ulx freeze
ulx gag
ulx gimp
ulx god
ulx goto
ulx hp
ulx ignite
ulx jail
ulx jailtp
ulx kick
ulx kickafternamechanges
ulx kickafternamechangescooldown
ulx kickafternamechangeswarning
ulx map
ulx mute
ulx noclip
ulx physgunplayer
ulx playsound
ulx ragdoll
ulx reservedslots
ulx rslots
ulx rslotsmode
ulx rslotsvisible
ulx seeanonymousechoes
ulx send
ulx showmotd
ulx slap
ulx slay
ulx showgroups
ulx showplayers
ulx spawnecho
ulx spectate
ulx sslay
ulx strip
ulx teleport
ulx tsay
ulx unban
ulx unblind
ulx uncloak
ulx unfreeze
ulx ungag
ulx ungimp
ulx ungod
ulx unignite
ulx unigniteall
ulx unjail
ulx unmute
ulx unragdoll
ulx veto
ulx vote
ulx voteban
ulx votebanminvotes
ulx votebansuccessratio
ulx votekick
ulx votekickminvotes
ulx votekicksuccessratio
ulx votemap2
ulx votemap2minvotes
ulx votemap2successratio
ulx votemapenabled
ulx votemapmapmode
ulx votemapmintime
ulx votemapminvotes
ulx votemapsuccessratio
ulx votemapvetotime
ulx votemapwaittime
ulx welcomemessage
ulx whip
ulx addgroup
ulx adduser
ulx adduserid
ulx addusermysql
ulx banid
ulx banuser
ulx cexec
ulx ent
ulx exec
ulx groupallow
ulx groupdeny
ulx hiddenecho
ulx logchat
ulx logdir
ulx logecho
ulx logechocolorconsole
ulx logechocolordefault
ulx logechocoloreveryone
ulx logechocolormisc
ulx logechocolorplayer
ulx logechocolorplayerasgroup
ulx logechocolors
ulx logechocolorself
ulx logevents
ulx logfile
ulx logjoinleaveecho
ulx logspawns
ulx logspawnsecho
ulx luarun
ulx maul
ulx rcon
ulx removeban
ulx removegroup
ulx removeuser
ulx removeuserid
ulx renamegroup
ulx setgroupcantarget
ulx sid
ulx updateuser
ulx userallow
ulx userallowid
ulx userdeny
ulx userdenyid
ulx voteecho
ulx seeasay
xgui_gmsettings
xgui_managebans
xgui_managegroups
xgui_svsettings